parameters:

services:
    puphpet.extension.percona.configure:
        class: Puphpet\Extension\PerconaBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.percona.front_controller:
        class: Puphpet\Extension\PerconaBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.percona.manifest_controller:
        class: Puphpet\Extension\PerconaBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
